config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index] do
    member do
      patch :ban
    end
  end
  resources :appointments do
    get :change_state
  end
  resources :patients
  resources :physicians
  resources :services
  resources :rooms do
    resources :messages
  end
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations', confirmations: 'users/confirmations' }
  
  root "pages#dashboard"
  get "check" => "appointments#check"
  devise_scope :user do
    get "pending" => "users/confirmations#pending"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/service.rb
class Service < ApplicationRecord
  validates :name, presence: true
  validates :price, numericality: { only_integer: true }

  has_many :appointments, dependent: :destroy

  enum status: { inactive: 0, active: 1 }, _prefix: :status
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @search = Service.ransack(params[:q])
    @pagy, @services = pagy(@search.result(distinct: true), items: 10)
  end

  # GET /services/1 or /services/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @service.to_json }
    end
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :price, :description, :status)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
  def status_collection
    return Service.statuses.map{ |k,v| [k.humanize.capitalize, v]}.push(["All statuses", ""]).reverse
  end

  def number_to_currency_vi(number)
    number_to_currency(number, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
  end

  def label_class(status)
    case status
    when 'inactive'
      return 'danger'
    when 'active'
      return 'success'
    else
      return 'info'
    end
  end
end

app/views/services/_form.html.erb
<%= form_with(model: service, html: {class: "col-md-10"}) do |form| %>
  <% if service.errors.any? %>
    <div style="color: red">
      <ul style="list-style: none">
        <% service.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <label class="form-label"><strong>Service name</strong></label>
    <%= form.text_field :name, class: "form-control mb-3", placeholder: "Enter name of service" %>
  </div>
  <div class="mb-3">
    <label class="form-label"><strong>Price</strong></label>
    <div class="input-group">
      <span class="input-group-text">VNĐ</span>
      <%= form.text_field :price, class: "form-control", placeholder: 100000 %>
      <span class="input-group-text">.00</span>
    </div>
  </div>
  <div class="mb-3">
    <label class="form-label"><strong>Description</strong></label>
    <%= form.text_area :description, class: "form-control", placeholder: "Describe a service..." %>
  </div>

  <div>
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/services/_service.html.erb
<tr class="table-secondary">
  <td><strong><%= service.name %></strong></td>
  <td><%= truncate(service.description, length: 100) %></td>
  <td><%= number_to_currency_vi(service.price) %></td>
  <td><span class="badge rounded-pill bg-<%= label_class(service.status) %>"><%= service.status.capitalize %></span></td>
  <td>
    <div class="dropdown">
      <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
        <i class="bi bi-three-dots-vertical"></i>
      </button>
      <div class="dropdown-menu">
        <%= link_to service_path(service), class: "dropdown-item" do %>
          <i class="bi bi-info-circle-fill me-1"></i> Show
        <% end %>
        <%= link_to edit_service_path(service), class: "dropdown-item" do %>
          <i class="bi bi-pencil-square me-1"></i> Edit
        <% end %>
        <%= button_to service, method: :delete, class: "dropdown-item" do %>
          <i class="bi bi-trash me-1"></i> Delete
        <% end %>
      </div>
    </div>
  </td>
</tr>

app/views/services/edit.html.erb
<h4 class="fw-bold py-3 mb-4">Editing service</h4>

<%= render "form", service: @service %>
<br>

<div>
  <%= link_to "Show this service", @service %> |
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between align-items-center">
  <h4 class="fw-bold py-3 mb-4">Services</h4>
  <%= link_to "New service", new_service_path, data: { turbo_frame: "second_frame" }, class: "btn btn-sm btn-outline-primary" %>
</div>

<%= search_form_for @search, url: services_path do |f| %>
  <div class="row gy-3 mb-3 align-items-center">
    <div class="col-lg-4 col-md-6">
      <div class="input-group">
        <span class="input-group-text"><i class="tf-icons bi bi-search"></i></span>
        <%= f.text_field :name_or_description_cont, class: "form-control", placeholder: "Search..." %>
        <%= f.submit "Search", class: "btn btn-primary" %>
      </div>
    </div>
    <div class="col-lg-2 col-md-3">
      <%= f.select :status_eq, options_for_select(status_collection, @search.status_eq), {}, { onchange: "this.form.submit()", class: "form-select" } %>
    </div>
  </div>
<% end %>

<%== render partial: 'pagy/pagination', locals: { pagy: @pagy } %>

<div class="card">
  <div class="table-responsive text-nowrap">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
        <tbody class="table-border-bottom-0">
            <%= render @services %>
        </tbody>
    </table>
  </div>
</div>

app/views/services/new.html.erb
<h4 class="fw-bold py-3 mb-4">New service</h4>

<%= render "form", service: @service %>
<br>

<div>
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service %>

<div>
  <%= link_to "Edit this service", edit_service_path(@service) %> |
  <%= link_to "Back to services", services_path %>

  <%= button_to "Destroy this service", @service, method: :delete %>
</div>