config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index] do
    member do
      patch :ban
    end
  end
  resources :appointments do
    get :change_state
  end
  resources :patients
  resources :physicians
  resources :services
  resources :rooms do
    resources :messages
  end
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations', confirmations: 'users/confirmations' }
  
  root "pages#dashboard"
  get "check" => "appointments#check"
  devise_scope :user do
    get "pending" => "users/confirmations#pending"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/physician.rb
class Physician < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments, dependent: :destroy
  accepts_nested_attributes_for :user

  has_one_attached :image
  
  # ransack_alias :user, :user_name_or_user_email_or_user_phone
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: %i[ show edit update destroy ]

  # GET /physicians or /physicians.json
  def index
    @search = Physician.ransack(params[:q])
    @pagy, @physicians = pagy(@search.result(distinct: true), items: 10)
  end

  # GET /physicians/1 or /physicians/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @physician.to_json(include: :user) }
    end
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
    @users = User.all
  end

  # GET /physicians/1/edit
  def edit
    @users = User.all
  end

  # POST /physicians or /physicians.json
  def create
    @physician = Physician.new(physician_params)
    @physician.image.attach(params[:physician][:image])

    respond_to do |format|
      if @physician.save
        format.html { redirect_to physician_url(@physician), notice: "Physician was successfully created." }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1 or /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to physician_url(@physician), notice: "Physician was successfully updated." }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1 or /physicians/1.json
  def destroy
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to physicians_url, notice: "Physician was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def physician_params
      params.require(:physician).permit(:user_id, :image, :degree, :education, :speciality, :experience, :about)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
  def rate(physician)
    appoointments = Appointment.joins(:physician).where(physician_id: physician.id).where(state: 2).where.not(rate: nil).pluck(:rate)
    count = appoointments.count
    sum = appoointments.inject(0) { |sum, x| sum + x }
    return (sum / count).to_f unless count == 0
  end

  def complete_count(physician)
    return Appointment.where(physician_id: physician.id).where(state: 2).count
  end
end

app/views/physicians/_physician.html.erb
<div id="<%= dom_id physician %>">
  <tr class="table-secondary">
    <td class="mw-px-50"><%= image_tag physician.image, class: "w-px-30 rounded-circle", style: "height: 30px" if physician.image.attached? %></td>
    <td><strong><%= physician.user.name %></strong></td>
    <td><%= number_to_phone_vi(physician.user.phone) %></td>
    <td><%= physician.speciality %></td>
    <td><%= physician.degree %></td>
    <td><span><i class="bi bi-star me-2" style="-webkit-text-stroke: 1px; color: #ee9b00"></i><small><strong><%= rate(physician) ? rate(physician) : 'N/A' %></strong></small></span></td>
    <td>
      <div class="dropdown">
        <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
          <i class="bi bi-three-dots-vertical"></i>
        </button>
        <div class="dropdown-menu">
          <%= link_to physician_path(physician), class: "dropdown-item" do %>
            <i class="bi bi-info-circle me-1"></i> Details
          <% end %>
          <%= link_to edit_physician_path(physician), class: "dropdown-item" do %>
            <i class="bi bi-pencil-square me-1"></i> Edit
          <% end %>
          <%= button_to physician, method: :delete, class: "dropdown-item" do %>
            <i class="bi bi-trash me-1"></i> Delete
          <% end %>
        </div>
      </div>
    </td>
  </tr>
</div>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render "form", physician: @physician %>

<br>

<div>
  <%= link_to "Show this physician", @physician %> |
  <%= link_to "Back to physicians", physicians_path %>
</div>

app/views/physicians/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between align-items-center">
  <h4 class="fw-bold py-3 mb-4">Physicians</h4>
  <%= link_to "New physician", new_physician_path, class: "btn btn-sm btn-outline-primary" %>
</div>

<%= search_form_for @search, url: physicians_path do |f| %>
  <div class="row gy-3 mb-3 align-items-center">
    <div class="col-lg-4 col-md-6">
      <div class="input-group">
        <span class="input-group-text"><i class="tf-icons bi bi-search"></i></span>
        <%= f.text_field :speciality_or_user_name_or_user_email_or_user_phone_cont, class: "form-control", placeholder: "Search..." %>
        <%= f.submit "Search", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<%== render partial: 'pagy/pagination', locals: { pagy: @pagy } %>

<div class="card">
  <div class="table-responsive text-nowrap">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Phone</th>
          <th>Speciality</th>
          <th>Degree</th>
          <th>Rate</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        <%= render @physicians %>
      </tbody>
    </table>
  </div>
</div>

app/views/physicians/new.html.erb
<h4 class="fw-bold py-3 mb-4">New physician</h4>

<%= render "form", physician: @physician %>

<br>

<div>
  <%= link_to "Back to physicians", physicians_path %>
</div>

app/views/physicians/show.html.erb
<p style="color: green">
  <%= notice %>
</p>

<div class="row">
  <div class="col-md-12">
    <div class="card mb-4">
    </div>
  </div>
  <div class="col-md mb-2">
    <div class="card h-100">
      <%= image_tag @physician.image, { class: "d-block rounded", height: "400", width: "400" } if @physician.image.attached? %>
      <div class="d-flex align-items-center mt-1 p-1">
        <div class="col-9">
          <p class="mb-0"><strong><%= @physician.user.name %></strong></p>
          <p class="mb-0"><small><%= number_to_phone_vi(@physician.user.phone) %></small></p>
        </div>
        <div class="col-3">
          <span>
            <i class="bi bi-star me-2" style="-webkit-text-stroke: 1px; color: #ee9b00"></i>
            <small><strong><%= rate(@physician) ? rate(@physician) : 'N/A' %></strong></small>
          </span>
          <p class="mb-0"><small>Appointments: <%= complete_count(@physician) %></small></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md">
    <dl class="row mt-2">
      <dt class="col-sm-3">Email</dt>
      <dd class="col-sm-9"><%= @physician.user.email %></dd>
  
      <dt class="col-sm-3">Degree</dt>
      <dd class="col-sm-9"><%= @physician.degree %></dd>
  
      <dt class="col-sm-3">Education</dt>
      <dd class="col-sm-9"><%= @physician.education %></dd>
  
      <dt class="col-sm-3">Speciality</dt>
      <dd class="col-sm-9"><%= @physician.speciality %></dd>
  
      <dt class="col-sm-3 text-truncate">Experience</dt>
      <dd class="col-sm-9"><%= @physician.experience %></dd>
  
      <dt class="col-sm-3">About</dt>
      <dd class="col-sm-9"><%= @physician.about %></dd>
    </dl>
  </div>
</div>

<div class="d-flex justify-content-between">
  <%= button_to "Destroy this physician" , @physician, method: :delete, class: "btn btn-danger" %>
  <div>
    <%= link_to "Edit this physician" , edit_physician_path(@physician) %> |
    <%= link_to "Back to physicians" , physicians_path %>
  </div>
</div>