config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index] do
    member do
      patch :ban
    end
  end
  resources :appointments do
    get :change_state
  end
  resources :patients
  resources :physicians
  resources :services
  resources :rooms do
    resources :messages
  end
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations', confirmations: 'users/confirmations' }
  
  root "pages#dashboard"
  get "check" => "appointments#check"
  devise_scope :user do
    get "pending" => "users/confirmations#pending"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments, dependent: :destroy
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @search = Patient.ransack(params[:q])
    @pagy, @patients = pagy(@search.result(distinct: true), items: 10)
  end

  # GET /patients/1 or /patients/1.json
  def show
    @pagy, @appointments = pagy(@patient.appointments.where(state: Appointment.states[:complete]), items: 10)
    respond_to do |format|
      format.html
      format.json { render json: @patient.to_json(include: :user) }
    end
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:address, user_attributes: [:email, :password, :name, :phone, :role])
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
  def last_visit(patient)
    last_visit = Appointment.where(patient_id: patient.id).where(state: 2).order(schedule: :desc).pluck(:schedule).first
    return last_visit ? last_visit.strftime("%d-%m-%Y") : "N/A"
  end
end

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xxl">
      <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between">
          <small class="text-muted float-end">Account</small>
        </div>
        <div class="card-body">
          <%= form.fields_for :user do |f| %>
            <div class="row mb-3">
              <%= form.label :name, class: "col-sm-2 col-form-label" %>
              <div class="col-sm-10">
                <%= form.text_field :name, class: "form-control", placeholder: "John Doe" %>
              </div>
            </div>
            <div class="row mb-3">
              <label class="col-sm-2 col-form-label" for="basic-default-email">Email</label>
              <div class="col-sm-10">
                <div class="input-group input-group-merge">
                  <input
                    type="text"
                    id="basic-default-email"
                    class="form-control"
                    placeholder="john.doe"
                    aria-label="john.doe"
                    aria-describedby="basic-default-email2"
                  />
                  <span class="input-group-text" id="basic-default-email2">@example.com</span>
                </div>
                <div class="form-text">You can use letters, numbers & periods</div>
              </div>
            </div>
            <div class="row mb-3">
              <label class="col-sm-2 col-form-label" for="basic-default-phone">Phone No</label>
              <div class="col-sm-10">
                <input
                  type="text"
                  id="basic-default-phone"
                  class="form-control phone-mask"
                  placeholder="658 799 8941"
                  aria-label="658 799 8941"
                  aria-describedby="basic-default-phone"
                />
              </div>
            </div>
            <div class="row justify-content-end">
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Send</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xxl">
      <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between">
          <small class="text-muted float-end">Patient informations</small>
        </div>
        <div class="card-body">
            <div class="row mb-3">
              <%= form.label :address, class: "col-sm-2 col-form-label" %>
              <div class="col-sm-10">
                <div class="input-group input-group-merge">
                  <span id="basic-icon-default-fullname2" class="input-group-text">
                    <i class="bi bi-geo-alt"></i>
                  </span>
                  <input
                    type="text"
                    class="form-control"
                    id="basic-icon-default-fullname"
                    placeholder="John Doe"
                    aria-label="John Doe"
                    aria-describedby="basic-icon-default-fullname2"
                  />
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <tr class="table-secondary">
    <td><strong><%= patient.user.name %></strong></td>
    <td><%= patient.user.email %></td>
    <td><%= patient.user.phone %></td>
    <td><%= patient.address %></td>
    <td><%= last_visit(patient) %></td>
    <td><span class="badge rounded-pill bg-<%= lock_badge_class(patient.user.access_locked?) %>"><%= patient.user.access_locked? ? "Locked" : "Active" %></span></td>
    <td>
      <div class="dropdown">
        <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
          <i class="bi bi-three-dots-vertical"></i>
        </button>
        <div class="dropdown-menu">
          <%= link_to patient_path(patient), class: "dropdown-item" do %>
            <i class="bi bi-info-circle me-1"></i> Details
          <% end %>
          <%= link_to edit_patient_path(patient), class: "dropdown-item" do %>
            <i class="bi bi-pencil-square me-1"></i> Edit
          <% end %>
          <%= button_to patient, method: :delete, class: "dropdown-item" do %>
            <i class="bi bi-trash me-1"></i> Delete
          <% end %>
        </div>
      </div>
    </td>
  </tr>
</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between align-items-center">
  <h4 class="fw-bold py-3 mb-4">Patients</h4>
  <%= link_to "New patients", new_patient_path, class: "btn btn-sm btn-outline-primary" %>
</div>

<%= search_form_for @search, url: patients_path, method: :get do |f| %>
  <div class="row gy-3 mb-3 align-items-center">
    <div class="col-lg-4 col-md-6">
      <div class="input-group">
        <span class="input-group-text"><i class="tf-icons bi bi-search"></i></span>
        <%= f.text_field :user_name_or_user_email_or_user_phone_or_address_cont, class: "form-control", placeholder: "Search..." %>
        <%= f.submit "Search", class: "btn btn-primary" %>
      </div>
    </div>
    <div class="col-lg-2 col-md-3">
      <%=  %>
    </div>
  </div>
<% end %>
<br>

<%== render partial: 'pagy/pagination', locals: { pagy: @pagy } %>

<div class="card">
  <div class="table-responsive text-nowrap">
    <table class="table">
      <thead>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Last visit</th>
        <th>Status</th>
        <th>Actions</th>
      </thead>
      <tbody class="table-border-bottom-0">
        <% @patients.each do |patient| %>
          <%= render patient %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/patients/new.html.erb
<h4 class="fw-bold py-3 mb-4">New patient</h4>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="mb-4">
  <div class="d-flex justify-content-between">
    <h6><strong>Patient infomations</strong></h6>
    <small>
      Account status:
      <span class="badge rounded-pill bg-<%= lock_badge_class(@patient.user.access_locked?) %>">
        <%= @patient.user.access_locked? ? "Locked" : "Active" %>
      </span>
    </small>
  </div>
  <div class="demo-inline-spacing mt-3 mb-5">
    <ul class="list-group">
      <li class="list-group-item d-flex align-items-center">
        <div class="col-sm-2">
          <i class="bi bi-person-vcard me-2"></i>
          Name:
        </div>
        <div class="col-sm-10">
          <%= @patient.user.name %>
        </div>
      </li>
      <li class="list-group-item d-flex align-items-center">
        <div class="col-sm-2">
          <i class="bi bi-envelope-at me-2"></i>
          Email:
        </div>
        <div class="col-sm-10">
          <%= @patient.user.email %>
        </div>
      </li>
      <li class="list-group-item d-flex align-items-center">
        <div class="col-sm-2">
          <i class="bi bi-telephone me-2"></i>
          Phone number:
        </div>
        <div class="col-sm-10">
          <%= number_to_phone_vi(@patient.user.phone) %>
        </div>
      </li>
      <li class="list-group-item d-flex align-items-center">
        <div class="col-sm-2">
          <i class="bi bi-geo-alt me-2"></i>
          Address:
        </div>
        <div class="col-sm-10">
          <%= @patient.address %>
        </div>
      </li>
      <li class="list-group-item d-flex align-items-center">
        <div class="col-sm-2">
          <i class="bi bi-calendar2-check me-2"></i>
          Last appointment:
        </div>
        <div class="col-sm-10">
          <%= last_visit(@patient) %>
        </div>
      </li>
    </ul>
  </div>
</div>

<h6><strong>Appointments history</strong></h6>

<% if @appointments.any? %>
  <%== render partial: 'pagy/pagination', locals: { pagy: @pagy } %>

  <div class="card">
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
              <th>Service</th>
              <th>Physician</th>
              <th>Schedule</th>
              <th>Diagnose</th>
              <th>State</th>
              <th>Created at</th>
          </tr>
        </thead>
        <tbody class="table-border-bottom-0">
          <% @appointments.each do |appointment| %>
            <tr>
              <td><%= appointment.service.name %></td>
              <td><%= appointment.physician.user.name %></td>
              <td><%= appointment.schedule.strftime("%H:%M %d-%m-%Y") %></td>
              <td></td>
              <td><span class="badge rounded-pill bg-<%= badge_class(appointment.state) %>"><%= appointment.state %></span></td>
              <td><%= appointment.created_at.strftime("%H:%M %d-%m-%Y") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <em>No record found!</em>
<% end %>

<div class="d-flex justify-content-between mt-5">
  <div>
    <%= link_to "Edit this patient", edit_patient_path(@patient) %> |
    <%= link_to "Back to patients", patients_path %>
  </div>
  <div>
    <%= button_to "Destroy this patient", @patient, method: :delete, class: "btn btn-danger" %>
  </div>
</div>