config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index] do
    member do
      patch :ban
    end
  end
  resources :appointments do
    get :change_state
  end
  resources :patients
  resources :physicians
  resources :services
  resources :rooms do
    resources :messages
  end
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations', confirmations: 'users/confirmations' }
  
  root "pages#dashboard"
  get "check" => "appointments#check"
  devise_scope :user do
    get "pending" => "users/confirmations#pending"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  require 'csv'

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << ["Patient", "Physician", "Service", "Schedule", "Note", "State", "Rate", "Comment"]
      all.each do |appoinment|
        csv << [appoinment.patient.user.name, appoinment.physician.user.name, appoinment.service.name, appoinment.schedule, appoinment.note, appoinment.state.capitalize, appoinment.rate, appoinment.comment]
      end
    end
  end

  attr_accessor :schedule_day, :schedule_time

  belongs_to :physician
  belongs_to :patient
  belongs_to :service

  before_validation do
    self.schedule = DateTime.parse([self.schedule_day, self.schedule_time].join(" ")) if self.schedule_day.present?
  end
  
  validates :service, presence: true
  validates :physician, presence: true
  validates :patient, presence: true

  enum state: {pending: 0, confirmed: 1, complete: 2, cancelled: 3}, _prefix: :state
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit -> { broadcast_append_to "room" }
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments, dependent: :destroy
end

app/models/physician.rb
class Physician < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments, dependent: :destroy
  accepts_nested_attributes_for :user

  has_one_attached :image
  
  # ransack_alias :user, :user_name_or_user_email_or_user_phone
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages

  scope :public_room, -> { where(is_private: false) }

  after_create_commit -> { broadcast_append_to "rooms", partial: "rooms/room", locals: { room: self }, target: "rooms" }
end

app/models/service.rb
class Service < ApplicationRecord
  validates :name, presence: true
  validates :price, numericality: { only_integer: true }

  has_many :appointments, dependent: :destroy

  enum status: { inactive: 0, active: 1 }, _prefix: :status
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :confirmable
  has_one :physician, dependent: :destroy
  has_one :patient, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_one_attached :avatar, dependent: :destroy

  enum role: {admin: 0, physician: 1, patient: 2}, _prefix: :role

  scope :all_except, ->(user) { where.not(id: user) }

  validates :name, presence: true

  before_create :default_avatar

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  private
    def default_avatar
      avatar.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'default_avatar.jpg'
          )
        ),
        filename: 'default_avatar.jpg',
        content_type: 'image/jpg'
      )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @public_rooms = Room.public_room
    @users = User.all_except(current_user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, noitice: "Channel was successfully created." }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    @public_rooms = Room.public_room
    @users = User.all_except(current_user)

    @message = Message.new
    @messages = @room.messages.order(created_at: :asc)

    render 'index'
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ ban ]
  def index
    @search = User.ransack(params[:q])
    @pagy, @users = pagy(@search.result(distinct: true).order(created_at: :asc), items: 10)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  def ban
    if @user.access_locked?
      @user.unlock_access!
    else
      @user.lock_access!
    end
    redirect_to users_path, notice: "Active changed successfully"
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def current_path?(path)
    return 'active' if request.path == path
    ''
  end

  def number_to_phone_vi(phone)
    number_to_phone(phone.sub!(/^0/, ""), country_code: 84) unless phone.blank?
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def states_collection
    return Appointment.states.map { |k,v| [k.humanize.capitalize, v] }.push(["All states", ""]).reverse
  end

  def badge_class(state)
    case state
    when 'pending'
      return 'warning'
    when 'confirmed'
      return 'primary'
    when 'complete'
      return 'success'
    when 'cancelled'
      return 'danger'
    else
      return 'info'
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
  def last_visit(patient)
    last_visit = Appointment.where(patient_id: patient.id).where(state: 2).order(schedule: :desc).pluck(:schedule).first
    return last_visit ? last_visit.strftime("%d-%m-%Y") : "N/A"
  end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
  def rate(physician)
    appoointments = Appointment.joins(:physician).where(physician_id: physician.id).where(state: 2).where.not(rate: nil).pluck(:rate)
    count = appoointments.count
    sum = appoointments.inject(0) { |sum, x| sum + x }
    return (sum / count).to_f unless count == 0
  end

  def complete_count(physician)
    return Appointment.where(physician_id: physician.id).where(state: 2).count
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def status_collection
    return Service.statuses.map{ |k,v| [k.humanize.capitalize, v]}.push(["All statuses", ""]).reverse
  end

  def number_to_currency_vi(number)
    number_to_currency(number, unit: "VNĐ", separator: ",", delimiter: ".", format: "%n %u")
  end

  def label_class(status)
    case status
    when 'inactive'
      return 'danger'
    when 'active'
      return 'success'
    else
      return 'info'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def role_collection
    User.roles.map{ |k,v| [k.humanize.capitalize, v] }.push(["All roles", ""]).reverse
  end

  def role_badge_class(role)
    case role
    when 'admin'
      return 'dark'
    when 'physician'
      return 'info'
    when 'patient'
      return 'primary'
    end
  end

  def lock_badge_class(lock)
    lock ? "danger" : "success"
  end
end

app/views/layouts/_footer.html.erb
<footer class="content-footer footer bg-footer-theme">
  <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
    <%# <div>
      <a href="https://themeselection.com/license/" class="footer-link me-4" target="_blank">License</a>
      <a href="https://themeselection.com/" target="_blank" class="footer-link me-4">More Themes</a>

      <a href="https://themeselection.com/demo/sneat-bootstrap-html-admin-template/documentation/" target="_blank"
        class="footer-link me-4">Documentation</a>

      <a href="https://github.com/themeselection/sneat-html-admin-template-free/issues" target="_blank"
        class="footer-link me-4">Support</a>
    </div> %>
  </div>
</footer>

app/views/layouts/_message.html.erb
<div>
  <% unless message.room.is_private %>
    <h6 class="name"> <%= message.user.username %> </h6>
  <% end %>
  <%= message.body %>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
    id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
      <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
        <i class="bi bi-list bx-sm"></i>
      </a>
    </div>
    
    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
      <ul class="navbar-nav flex-row align-items-center ms-auto">
        <li class="nav-item navbar-dropdown dropdown">
          <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
            <i class="bi bi-bell-fill me-2"></i>
          </a>
          <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="alertsDropdown">
            <h6 class="dropdown-header text-white text-uppercase" style="font-weight: 800; background-color: var(--bs-primary)">
                Alerts Center
            </h6>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="mr-3">
                <div class="icon-circle bg-primary">
                    <i class="fas fa-file-alt text-white"></i>
                </div>
              </div>
              <div>
                <div class="small text-gray-500">December 12, 2019</div>
                <span class="font-weight-bold">A new monthly report is ready to download!</span>
              </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="mr-3">
                <div class="icon-circle bg-success">
                    <i class="fas fa-donate text-white"></i>
                </div>
              </div>
              <div>
                <div class="small text-gray-500">December 7, 2019</div>
                $290.29 has been deposited into your account!
              </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="mr-3">
                <div class="icon-circle bg-warning">
                    <i class="fas fa-exclamation-triangle text-white"></i>
                </div>
              </div>
              <div>
                <div class="small text-gray-500">December 2, 2019</div>
                Spending Alert: We've noticed unusually high spending for your account.
              </div>
            </a>
            <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
          </div>
        <li>
        <li class="nav-item navbar-dropdown dropdown">
          <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
            <i class="bi bi-envelope-fill me-2"></i>
            <%# <span class="badge bg-danger bg-counter">7</span> %>
          </a>
          <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
            <h5 class="dropdown-header text-white text-uppercase" style="font-weight: 800; background-color: var(--bs-primary)">
                Message Center
            </h5>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="dropdown-list-image mr-3">
                  <img class="rounded-circle" src="" alt="...">
                  <div class="status-indicator bg-success"></div>
              </div>
              <div class="font-weight-bold">
                  <div class="text-truncate">Hi there! I am wondering if you can help me with a
                      problem I've been having.</div>
                  <div class="small">Emily Fowler · 58m</div>
              </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="" alt="...">
                    <div class="status-indicator"></div>
                </div>
                <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how
                        would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="" alt="...">
                    <div class="status-indicator bg-warning"></div>
                </div>
                <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with
                        the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="...">
                    <div class="status-indicator bg-success"></div>
                </div>
                <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                        told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                </div>
            </a>
            <%= link_to "Read more messages", rooms_path, class: "dropdown-item text-center small" %>
          </div>
        <li>
      
        <!-- User -->
        <li class="nav-item navbar-dropdown dropdown-user dropdown">
          <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
            <span class="me-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
            <%# <div class="avatar avatar-online"> %>
            <%= image_tag(current_user.avatar, class: "w-px-40 h-auto rounded-circle") if current_user.avatar.attached? %>
            <%# </div> %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li>
              <a class="dropdown-item" href="#">
                <div class="d-flex">
                  <div class="flex-shrink-0 me-3">
                    <div class="avatar avatar-online">
                      <%= image_tag(current_user.avatar, class: "w-px-40 h-auto rounded-circle") if current_user.avatar.attached? %>
                    </div>
                  </div>
                  <div class="flex-grow-1">
                    <span class="fw-semibold d-block"><%= current_user.name %></span>
                    <small class="text-muted"><%= current_user.role.capitalize %></small>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <div class="dropdown-divider"></div>
            </li>
            <li>
              <%= link_to user_registration_path, class: "dropdown-item" do %>
                <i class="bi bi-person-circle me-2"></i>
                <span class="align-middle">My profile</span>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <i class="bi bi-gear me-2"></i>
                <span class="align-middle">Settings</span>
              <% end %>
            </li>
            <li>
              <div class="dropdown-divider"></div>
            </li>
            <li>
              <%= button_to destroy_user_session_path, method: :delete, data: {"turbo": false}, class: "dropdown-item btn btn-outline-danger" do %>
                <i class="bi bi-power"></i> Log Out
              <% end %>
            </li>
          </ul>
        </li>
        <!--/ User -->
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>
  <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
      <%= link_to root_path, class: "app-brand-link" do %>
        <span class="app-brand-logo demo">
          <svg width="25" viewBox="0 0 25 42" version="1.1" xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink">
            <defs>
              <path
                d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                id="path-1"></path>
              <path
                d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                id="path-3"></path>
              <path
                d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                id="path-4"></path>
              <path
                d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                id="path-5"></path>
            </defs>
            <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                <g id="Icon" transform="translate(27.000000, 15.000000)">
                  <g id="Mask" transform="translate(0.000000, 8.000000)">
                    <mask id="mask-2" fill="white">
                      <use xlink:href="#path-1"></use>
                    </mask>
                    <use fill="#696cff" xlink:href="#path-1"></use>
                    <g id="Path-3" mask="url(#mask-2)">
                      <use fill="#696cff" xlink:href="#path-3"></use>
                      <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                    </g>
                    <g id="Path-4" mask="url(#mask-2)">
                      <use fill="#696cff" xlink:href="#path-4"></use>
                      <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                    </g>
                  </g>
                  <g id="Triangle"
                    transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) ">
                    <use fill="#696cff" xlink:href="#path-5"></use>
                    <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                  </g>
                </g>
              </g>
            </g>
          </svg>
        </span>
        <span class="app-brand-text demo menu-text fw-bolder ms-2">EHealth</span>
      <% end %>
      <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
        <i class="bx bx-chevron-left bx-sm align-middle"></i>
      </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
      <!-- Dashboard -->
      <li class="menu-item <%= current_path?(root_path) %>">
        <%= link_to root_path, class: "menu-link" do %>
          <i class="menu-icon tf-icons bi bi-house-heart"></i>
          <div data-i18n="Analytics">Dashboard</div>
        <% end %>
      </li>
      <li class="menu-header small text-uppercase">
        <span class="menu-header-text">Users</span>
      </li>
      <li class="menu-item <%= current_path?(users_path) %>">
        <%= link_to users_path, class: "menu-link" do %>
          <i class="menu-icon tf-icons bi bi-people"></i>
          <div data-i18n="Tables">Users account</div>
        <% end %>
      </li>
      <li class="menu-item <%= current_path?(physicians_path) %>">
        <%= link_to physicians_path, class: "menu-link" do %>
          <i class="menu-icon tf-icons bi bi-person-badge"></i>
          <div data-i18n="Tables">Physicians</div>
        <% end %>
      </li>
      <li class="menu-item <%= current_path?(patients_path) %>">
        <%= link_to patients_path, class: "menu-link" do %>
          <i class="menu-icon tf-icons bi bi-person-hearts"></i>
          <div data-i18n="Tables">Patients</div>
        <% end %>
      </li>
      <li class="menu-header small text-uppercase">
        <span class="menu-header-text">Services</span>
      </li>
      <li class="menu-item <%= current_path?(services_path) %>">
        <%= link_to services_path, class: "menu-link" do %>
          <i class="menu-icon tf-icons bi bi-bandaid-fill"></i>
          <div data-i18n="Tables">Services</div>
        <% end %>
      </li>
      <li class="menu-header small text-uppercase">
        <span class="menu-header-text">Appointments</span>
      </li>
      <li class="menu-item <%= current_path?(appointments_path) %>">
        <%= link_to appointments_path, class: "menu-link" do %>
          <i class="menu-icon tf-icons bi bi-calendar-event"></i>
          <div data-i18n="Tables">Appointments</div>
        <% end %>
      </li>
      <li class="menu-header small text-uppercase">
        <span class="menu-header-text">Chat</span>
      </li>
      <li class="menu-item <%= current_path?(rooms_path) %>">
        <%= link_to rooms_path, class: "menu-link" do %>
          <i class="menu-icon tf-icons bi bi-chat-dots"></i>
          <div data-i18n="Tables">Messenger</div>
        <% end %>
      </li>
    </ul>
  </aside>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>eHealth</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "main" %>
    <%= javascript_include_tag "menu" %>
    <%= javascript_include_tag "helpers" %>
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"/>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
          <%= render 'layouts/sidebar' %>
          <div class="layout-page">
            <%= render 'layouts/navbar' %>
            <div class="content-wrapper">
              <div class="container-xxl flex-grow-1 container-p-y">
                <%= yield %>
                <% flash.each do |message_type, message| %>
                  <div class="alert alert-<%= message_type %>"><%= message %></div>
                <% end %>
              </div>
              <%= render 'layouts/footer' %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/pagy/_pagination.html.erb
<% link = pagy_link_proc(pagy) %>
<nav aria-label="Page navigation">
  <ul class="pagination pagination-sm justify-content-center">
    <% if pagy.prev %>
      <li class="page-item prev">
        <%== link.call(pagy.prev, '<i class="bi bi-chevron-left"></i>', 'class="page-link"') %>
      </li>
    <% else %>
      <li class="page-item prev disabled">
        <%== link.call(1, '<i class="bi bi-chevron-left"></i>', 'class="page-link"') %>
      </li>
    <% end %>
    <% pagy.series.each do |item| %>
      <% if item.is_a?(Integer) %>
        <li class="page-item">
          <%== link.call(item, item, 'class="page-link"') %>
        </li>
      <% elsif item.is_a?(String) %>
        <li class="page-item active">
          <%== link_to(item, "javascript:void(0)", class: "page-link") %>
        </li>
      <% elsif item == :gap %>
        <li class="page-item disabled">
          <%== link_to("...", "javascript:void(0)", class: "page-link") %>
        </li>
      <% end %>
    <% end %>
    <% if pagy.next %>
      <li class="page-item next">
        <%== link.call(pagy.next, '<i class="bi bi-chevron-right"></i>', 'class="page-link"') %>
      </li>
    <% else %>
      <li class="page-item next disabled">
        <%== link.call(pagy.last, '<i class="bi bi-chevron-right"></i>', 'class="page-link"') %>
      </li>
    <% end %>
  </ul>
</nav>